import type { Metadata } from "next";
import { Prompt, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const prompt = Prompt({
  subsets: ["thai"],
  variable: "--font-prompt",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Loy Krathongday",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <>
        <title>Loy Krathongday</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </>
      <body
        className={`${prompt.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
